"""A game about pride flags. :)"""
#python -m hack.hackathon


from turtle import Turtle, bgcolor, update, done, onkey, listen, tracer, ontimer
from typing import Dict, List
import random


t1: Turtle = Turtle()
correct: Turtle = Turtle()
incorrect: Turtle = Turtle()
n_duck: Turtle = Turtle()
bi: Turtle = Turtle()


def main() -> None:
    """This bad boy can fit a whole lot of code B) (entrypoint to program)"""
    tracer(0,0)
    bgcolor("mistyrose")
    #q2()
    #neutral_duck_sprite()
    bi_flag()
    q_function_list = [q1, q2]
    #put all question functions in this list so that I can randomly access them
    for q in range(10):
        fn = random.choice(q_function_list)
        fn()
    #update()
    done()  

def select_answer() -> None:
    correct.hideturtle()
    correct.write("That's correct!")

def select_incorrect() -> None:
    incorrect.hideturtle()
    incorrect.write("Sorry, that's not correct.")


def q1() -> None:
    """What flag -> trans."""
    t1.hideturtle()
    t1.penup()
    t1.setposition(-235, 180)
    t1.pendown()
    t1.pencolor("lightcoral")
    t1.write("What community does this flag represent?", move=False, align="left", font=("Century Gothic", 17, "bold"))
    t1.penup()
    t1.left(90)
    t1.forward(400)
    t1.pendown()
    t1.write("Trans", move=False, align="left", font=("Century Gothic", 17, "bold"))
    t1.penup()
    t1.left(90)
    t1.forward(175)
    t1.pendown()
    t1.write("Bisexual", move=False, align="left", font=("Century Gothic", 17, "bold"))
    t1.penup()
    t1.forward(175)
    t1.pendown()
    t1.write("Pansexual", move=False, align="left", font=("Century Gothic", 17, "bold"))

    onkey(select_answer, "a")
    onkey(select_incorrect, "s")
    onkey(select_incorrect, "d")
    listen()

    
def q2() -> None:
    """What flag -> nonbinary."""
    t1.hideturtle()
    t1.penup()
    t1.setposition(-235, 180)
    t1.pendown()
    t1.pencolor("lightcoral")
    t1.write("What community does this flag represent?", move=False, align="left", font=("Century Gothic", 17, "bold"))
    t1.penup()
    t1.left(90)
    t1.forward(400)
    t1.pendown()
    t1.write("Trans", move=False, align="left", font=("Century Gothic", 17, "bold"))
    t1.penup()
    t1.left(90)
    t1.forward(160)
    t1.pendown()
    t1.write("Nonbinary", move=False, align="left", font=("Century Gothic", 17, "bold"))
    t1.penup()
    t1.forward(175)
    t1.pendown()
    t1.write("Intersex", move=False, align="left", font=("Century Gothic", 17, "bold"))

    onkey(select_answer, "a")
    onkey(select_incorrect, "s")
    onkey(select_incorrect, "d")
    listen()


def neutral_duck_sprite() -> None:
    n_duck.hideturtle()
    n_duck.penup()
    n_duck.pencolor("gold")
    n_duck.pendown()
    n_duck.fillcolor("gold")
    n_duck.begin_fill()
    n_duck.forward(24)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.left(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(24)
    n_duck.left(90)
    n_duck.forward(32)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.left(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.left(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.left(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(48)
    n_duck.right(90)
    n_duck.forward(32)
    n_duck.left(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.left(90)
    n_duck.forward(16)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.left(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.left(90)
    n_duck.forward(8)
    n_duck.end_fill()
    n_duck.penup()
    n_duck.right(180)
    n_duck.forward(8)
    n_duck.pencolor("black")
    n_duck.fillcolor("black")
    n_duck.begin_fill()
    n_duck.pendown()
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.end_fill()
    n_duck.penup()
    n_duck.left(90)
    n_duck.forward(8)
    n_duck.begin_fill()
    n_duck.pendown()
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.end_fill()
    n_duck.penup()
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.pencolor("orange")
    n_duck.fillcolor("orange")
    n_duck.begin_fill()
    n_duck.pendown()
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(32)
    n_duck.right(90)
    n_duck.forward(8)
    n_duck.right(90)
    n_duck.forward(32)
    n_duck.end_fill()

def bi_flag() -> None:
    bi.hideturtle()
    bi.pencolor("deeppink")
    bi.fillcolor("deeppink")
    bi.begin_fill()
    bi.pendown()
    bi.forward(200)
    bi.right(90)
    bi.forward(50)
    bi.right(90)
    bi.forward(200)
    bi.right(90)
    bi.forward(50)
    bi.end_fill()
    bi.penup()
    bi.right(180)
    bi.forward(50)
    bi.pencolor("mediumorchid")
    bi.fillcolor("mediumorchid")
    bi.begin_fill()
    bi.pendown()
    bi.forward(50)
    bi.left(90)
    bi.forward(200)
    bi.left(90)
    bi.forward(50)
    bi.left(90)
    bi.forward(200)
    bi.end_fill()
    bi.penup()
    bi.left(90)
    bi.forward(50)
    bi.pencolor("mediumblue")
    bi.fillcolor("mediumblue")
    bi.begin_fill()
    bi.pendown()
    bi.forward(50)
    bi.left(90)
    bi.forward(200)
    bi.left(90)
    bi.forward(50)
    bi.left(90)
    bi.forward(200)
    bi.end_fill()
    bi.penup()


if __name__ == "__main__":
    main()

